CUDA and MPS are not available. Using CPU.
CUDA and MPS are not available. Using CPU.
Traceback (most recent call last):
  File "/home/cyuting/Test/./Generalized_classifier_trainer.py", line 37, in <module>
    data, label = dpc.data_process()
  File "/home/cyuting/Test/DataProcess_Classifier.py", line 98, in data_process
    user_re[i,k,j]=df[j+i*interval_day,k]
IndexError: index 3471 is out of bounds for axis 0 with size 3471
